apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{ .values.selectors | nindent 4 }}
