# Define deployment environments
environments:
  staging:

helmDefaults:
  createNamespace: true
  wait: true

releases:
- name: postgres
  namespace: postgres
  chart: .
  values:
    - values.yaml
    - ./vars/{{ .Environment.Name }}/values.yaml

